# Go音频服务器配置文件
server:
  host: "0.0.0.0"
  port: 8080
  static_dir: "../static"
  upload_dir: "../uploads"
database:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "shen2003125"
  name: "musicdb"
redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
